const mongoose = require("mongoose");
const Product = require("./Product");

// Connect to MongoDB
mongoose.connect("mongodb://127.0.0.1:27017/mobileshop", {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// Sample product data
const products = [
  // 🍎 Apple
  {
    id: 1,
    name: "iPhone 15 Pro",
    image: "/images/Products/iphone15pro.png",
    brand: "Apple",
    brandImage: "/images/Brand/Apple.png",
    price: 1299,
    category: "Smartphone",
    stock: 10,
    status: "active",
  },
  {
    id: 2,
    name: "iPhone 14 Pro Max",
    image: "/images/Products/iphone14promax.png",
    brand: "Apple",
    brandImage: "/images/Brand/Apple.png",
    price: 1199,
    category: "Smartphone",
    stock: 8,
    status: "active",
  },
  {
    id: 3,
    name: "iPhone 13",
    image: "/images/Products/iphone13.png",
    brand: "Apple",
    brandImage: "/images/Brand/Apple.png",
    price: 999,
    category: "Smartphone",
    stock: 15,
    status: "active",
  },
  {
    id: 4,
    name: "iPhone SE",
    image: "/images/Products/iphonese.png",
    brand: "Apple",
    brandImage: "/images/Brand/Apple.png",
    price: 499,
    category: "Smartphone",
    stock: 25,
    status: "active",
  },
  {
    id: 5,
    name: "iPhone 12 Mini",
    image: "/images/Products/iphone12mini.png",
    brand: "Apple",
    brandImage: "/images/Brand/Apple.png",
    price: 799,
    category: "Smartphone",
    stock: 18,
    status: "active",
  },

  // 📱 Samsung
  {
    id: 6,
    name: "Samsung Galaxy S24 Ultra",
    image: "/images/Products/s24ultra.png",
    brand: "Samsung",
    brandImage: "/images/Brand/Samsung.png",
    price: 1199,
    category: "Smartphone",
    stock: 12,
    status: "active",
  },
  {
    id: 7,
    name: "Samsung Galaxy S23",
    image: "/images/Products/s23.png",
    brand: "Samsung",
    brandImage: "/images/Brand/Samsung.png",
    price: 1099,
    category: "Smartphone",
    stock: 9,
    status: "active",
  },
  {
    id: 8,
    name: "Samsung Galaxy A54",
    image: "/images/Products/a54.png",
    brand: "Samsung",
    brandImage: "/images/Brand/Samsung.png",
    price: 599,
    category: "Smartphone",
    stock: 20,
    status: "active",
  },
  {
    id: 9,
    name: "Samsung Galaxy Z Fold 5",
    image: "/images/Products/zfold5.png",
    brand: "Samsung",
    brandImage: "/images/Brand/Samsung.png",
    price: 1499,
    category: "Smartphone",
    stock: 5,
    status: "active",
  },
  {
    id: 10,
    name: "Samsung Galaxy M14",
    image: "/images/Products/m14.png",
    brand: "Samsung",
    brandImage: "/images/Brand/Samsung.png",
    price: 299,
    category: "Smartphone",
    stock: 30,
    status: "active",
  },

  // 🔵 Vivo
  {
    id: 11,
    name: "Vivo X100",
    image: "/images/Products/vivox100.png",
    brand: "Vivo",
    brandImage: "/images/Brand/Vivo.png",
    price: 699,
    category: "Smartphone",
    stock: 20,
    status: "active",
  },
  {
    id: 12,
    name: "Vivo V29",
    image: "/images/Products/vivov29.png",
    brand: "Vivo",
    brandImage: "/images/Brand/Vivo.png",
    price: 399,
    category: "Smartphone",
    stock: 18,
    status: "active",
  },
  {
    id: 13,
    name: "Vivo T2",
    image: "/images/Products/vivot2.png",
    brand: "Vivo",
    brandImage: "/images/Brand/Vivo.png",
    price: 349,
    category: "Smartphone",
    stock: 22,
    status: "active",
  },
  {
    id: 14,
    name: "Vivo Y200",
    image: "/images/Products/vivoy200.png",
    brand: "Vivo",
    brandImage: "/images/Brand/Vivo.png",
    price: 299,
    category: "Smartphone",
    stock: 25,
    status: "active",
  },
  {
    id: 15,
    name: "Vivo X90 Pro",
    image: "/images/Products/vivox90pro.png",
    brand: "Vivo",
    brandImage: "/images/Brand/Vivo.png",
    price: 899,
    category: "Smartphone",
    stock: 10,
    status: "active",
  },

  // 🟡 Realme
  {
    id: 16,
    name: "Realme Narzo 60 Pro",
    image: "/images/Products/narzo60pro.png",
    brand: "Realme",
    brandImage: "/images/Brand/Realme.png",
    price: 499,
    category: "Smartphone",
    stock: 30,
    status: "active",
  },
  {
    id: 17,
    name: "Realme 11x",
    image: "/images/Products/realme11x.png",
    brand: "Realme",
    brandImage: "/images/Brand/Realme.png",
    price: 299,
    category: "Smartphone",
    stock: 15,
    status: "active",
  },
  {
    id: 18,
    name: "Realme GT Neo 5",
    image: "/images/Products/gtneo5.png",
    brand: "Realme",
    brandImage: "/images/Brand/Realme.png",
    price: 649,
    category: "Smartphone",
    stock: 12,
    status: "active",
  },
  {
    id: 19,
    name: "Realme C55",
    image: "/images/Products/c55.png",
    brand: "Realme",
    brandImage: "/images/Brand/Realme.png",
    price: 249,
    category: "Smartphone",
    stock: 20,
    status: "active",
  },
  {
    id: 20,
    name: "Realme 10 Pro+",
    image: "/images/Products/10proplus.png",
    brand: "Realme",
    brandImage: "/images/Brand/Realme.png",
    price: 499,
    category: "Smartphone",
    stock: 18,
    status: "active",
  },

  // 🟣 Oppo
  {
    id: 21,
    name: "Oppo Reno 10",
    image: "/images/Products/reno10.png",
    brand: "Oppo",
    brandImage: "/images/Brand/Oppo.png",
    price: 599,
    category: "Smartphone",
    stock: 14,
    status: "active",
  },
  {
    id: 22,
    name: "Oppo F23",
    image: "/images/Products/f23.png",
    brand: "Oppo",
    brandImage: "/images/Brand/Oppo.png",
    price: 349,
    category: "Smartphone",
    stock: 16,
    status: "active",
  },
  {
    id: 23,
    name: "Oppo A78",
    image: "/images/Products/a78.png",
    brand: "Oppo",
    brandImage: "/images/Brand/Oppo.png",
    price: 299,
    category: "Smartphone",
    stock: 20,
    status: "active",
  },
  {
    id: 24,
    name: "Oppo Find N3 Flip",
    image: "/images/Products/n3flip.png",
    brand: "Oppo",
    brandImage: "/images/Brand/Oppo.png",
    price: 1299,
    category: "Smartphone",
    stock: 8,
    status: "active",
  },
  {
    id: 25,
    name: "Oppo K10",
    image: "/images/Products/k10.png",
    brand: "Oppo",
    brandImage: "/images/Brand/Oppo.png",
    price: 229,
    category: "Smartphone",
    stock: 25,
    status: "active",
  },
];

// Insert products into the database
Product.insertMany(products)
  .then(() => {
    console.log("✅ Products inserted successfully!");
    mongoose.connection.close();
  })
  .catch((err) => {
    console.error("❌ Error inserting products:", err);
  });
